# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lab4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lab4
  pod 'Masonry'
  pod 'SDWebImage'
  target 'lab4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'lab4UITests' do
    # Pods for testing
  end

end
