# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lab3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lab3
  pod 'SDWebImage'
  pod 'Masonry'
  target 'lab3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'lab3UITests' do
    # Pods for testing
  end

end
